config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  root to: 'user/videogames#index'
    

  namespace :admins do
      get '/account' => 'accounts#edit', as: :account
      put '/info' => 'accounts#update_info', as: :info
      put '/password' => 'accounts#update_password', as: :password
      resources :videogames
  end
    
    scope module: 'user' do
        get 'about' => 'pages#about', as: :about
        get 'contact' => 'pages#contact', as: :contact
        get 'videogames' => 'videogames#index', as: :videogames
        get 'videogames/:id' => 'videogames#show', as: :videogame
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
    
  has_many :videogames
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/videogame.rb
class Videogame < ApplicationRecord
    
    extend FriendlyId
    friendly_id :name, use: :slugged
    
    belongs_to :admin

    
    scope :most_recent, -> {order(id: :desc) } 
    
    def should_generate_new_friendly_id?
        slug.blank? || name_changed?
    end
    
    def display_date_published
        "#{created_at.strftime('%-b %-d, %Y')}";
    end
        
end

app/controllers/admins/accounts_controller.rb
module Admins
    class AccountsController < AdminsController
        def edit
        end
        def update_info
          if current_admin.update(admin_info_params)
            flash[:success] = 'Successfully saved info.'
          else
            flash[:danger] = current_admin.display_error_messages
          end
          redirect_to admins_account_path
        end

        def update_password

        end

        private

        def admin_info_params
          params.require(:admin).permit(:name, :email, :bio)
        end

        def admin_password_params
          params.require(:admin).permit(:current_password, :new_password, :new_password_confirmation)
        end

      end
end

app/controllers/admins/videogames_controller.rb
module Admins
    class VideogamesController < AdminsController
        before_action :set_videogame, only: [:show, :edit, :update, :destroy]

        # GET /videogames
        # GET /videogames.json
        def index
            @videogames = current_admin.videogames.most_recent
        end

        # GET /videogames/1
        # GET /videogames/1.json
        def show
        end

        # GET /videogames/new
        def new
            @videogame = current_admin.videogames.new
        end

        # GET /videogames/1/edit
        def edit
        end

        # POST /videogames
        # POST /videogames.json
        def create
            @videogame = current_admin.videogames.new(videogame_params)

            respond_to do |format|
                if @videogame.save
                    format.html { redirect_to admins_videogame_path(@videogame), notice: 'Videogame was successfully created.' }
                    format.json { render :show, status: :created, location: @videogame }
                else
                    format.html { render :new }
                    format.json { render json: @videogame.errors, status: :unprocessable_entity }
                end
            end
        end

      # PATCH/PUT /videogames/1
      # PATCH/PUT /videogames/1.json
        def update
            respond_to do |format|
                if @videogame.update(videogame_params)
                    format.html { redirect_to admins_videogame_path(@videogame), notice: 'Videogame was successfully updated.' }
                    format.json { render :show, status: :ok, location: @videogame }
                else
                    format.html { render :edit }
                    format.json { render json: @videogame.errors, status: :unprocessable_entity }
                end
            end
        end

      # DELETE /videogames/1
      # DELETE /videogames/1.json
        def destroy
            @videogame.destroy
            respond_to do |format|
                format.html { redirect_to admins_videogames_url, notice: 'Videogame was successfully destroyed.' }
                format.json { head :no_content }
            end
        end

        private
        # Use callbacks to share common setup or constraints between actions.
            def set_videogame
                @videogame = current_admin.videogames.friendly.find(params[:id])
            end

        # Never trust parameters from the scary internet, only allow the white list through.
        def videogame_params
          params.require(:videogame).permit(:name, :description, :image)
        end
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
    layout 'admins'
    
end

app/controllers/user/pages_controller.rb
module User
    class PagesController < UserController
    
        def about
        end
    
        def contact
        end
    end
end

app/controllers/user/videogames_controller.rb
module User
    class VideogamesController < UserController

    # GET /videogames
    # GET /videogames.json
        def index
            @videogames = Videogame.most_recent
        end

        # GET /videogames/1
        # GET /videogames/1.json
        def show
            @videogame = Videogame.friendly.find(params[:id])
        end
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videogames_helper.rb
module VideogamesHelper
end

app/views/admins/accounts/edit.html.erb
<% provide(:page_title, 'Account Settings') %>
<div class="row">
    <%= form_tag admins_info_path, method: :put do %>
    <%= fields_for :admin do |f| %>
      <div class="col-md-6">
        <div class="card">
          <div class="card-block">
            <div class="card-title">
              Basic info
            </div>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="field">
                <%= f.label :name %>
                <%= f.text_field :name, value: current_admin.name, class: 'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :email %>
                <%= f.text_field :email, value: current_admin.email, class: 'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :bio %>
                <%= f.text_area :bio, value: current_admin.bio, class: 'form-control' %>
              </div>
            </li>
            <li class='list-group-item'>
              <%= f.submit "Update info", class: 'btn btn-primary' %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
    <% end %>
    
    <%= form_tag admins_password_path method: :put do %>
    <%= fields_for :admin do |f| %>
    <div class="col-md-6">
        <div class="card">
          <div class="card-block">
            <div class="card-title">
              Change password
            </div>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="field">
                <%= f.label :current_password %>
                <%= f.password_field :current_password, class: 'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :new_password %>
                <%= f.password_field :new_password, class: 'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :new_password_confirmation %>
                <%= f.password_field :new_password_confirmation, class: 'form-control' %>
              </div>
            </li>
            <li class='list-group-item'>
              <%= f.submit "Change password", class: 'btn btn-primary', disabled: "true"%>
            </li>
          </ul>
        </div>
    </div>
    <% end %>
    <% end %>
</div>

app/views/admins/videogames/_form.html.erb
<%= form_for(videogame, url: url) do |f| %>
  <% if videogame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(videogame.errors.count, "error") %> prohibited this videogame from being saved:</h2>

      <ul>
      <% videogame.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-md-3">
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          
          <div class="form-group">
            <%= f.label :image %>
            <%= f.text_field :image, class: "form-control", placeholder: "Image Url" %>
          </div>
      </div>
      <div class="col-md-9">
        <div class="form-group">
            <label for="exampleTextarea"><%= f.label :description %></label>
            <%= f.text_area :description, class: "form-control", rows: "3" %>
        </div>          
      </div>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/admins/videogames/_videogame.html.erb
<tr>
    <td><%= link_to videogame.name, admins_videogame_path(videogame) %></td>
    <td></td>
    <td><%= link_to 'Edit', edit_admins_videogame_path(videogame), class: 'btn btn-sm btn-warning' %> </td>
    <td><%= link_to 'Remove', admins_videogame_path(videogame), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %> </td>
</tr>

app/views/admins/videogames/edit.html.erb
<% provide(:page_title, "Edit #{@videogame.name}") %>
<% provide(:admins, 'active') %>

<h1>Editing Videogame</h1>

<%= render 'form', videogame: @videogame, url: admins_videogame_url(@videogame)  %>

<%= link_to 'Show', @videogame %> |
<%= link_to 'Back', admins_videogames_path %>

app/views/admins/videogames/index.html.erb
<% provide(:page_title, 'Home') %>
<% provide(:admins, 'active') %>

<div class="row">
    <div>
        <%= link_to 'New', new_admins_videogame_path, class: 'btn btn-primary btn-lg' %>
    </div>
    <br>
    <table class="table table-striped">
        <tr>
            <th colspan="4">Name</th>
        </tr>
        <% @videogames.each do |videogame| %>
            <%= render videogame %>
        <% end %>
    </table>

</div>

app/views/admins/videogames/new.html.erb
<% provide(:page_title, 'New Videogame') %>
<% provide(:admins, 'active') %>

<h1>New Videogame</h1>

<%= render 'form', videogame: @videogame, url: admins_videogames_url %>

<%= link_to 'Back', admins_videogames_path %>

app/views/admins/videogames/show.html.erb
<% provide(:page_title, @videogame.name) %>
<% provide(:admins, 'active') %>

<div>
    <%= link_to 'Edit', edit_admins_videogame_path(@videogame), class: 'btn btn-sm btn-warning' %>
    <%= link_to 'Remove', admins_videogame_path(@videogame), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
</div>
<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @videogame.name %></h1>
    <p><%= @videogame.display_date_published %></p>
    <%= @videogame.description%>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="collapse navbar-collapse justify-content-end" id="exCollapsingNavbar">
  <div class="collapse-bg p-a-1">
    <div class='card'>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
        <% if admin_signed_in? %> 
            <li class="list-group-item">
              <%= link_to 'My posts', admins_videogames_path, class: "nav-link #{yield(:admins)}" %>
            </li>
          <li class="list-group-item">
                <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class: "nav-link" %> 
            </li>
        <% end %>  
      </ul>
    </div>
  </div>
</div>

<nav class="navbar navbar-light bg-faded">
  <div class='container'>
    <a class='navbar-brand' href='/'>
      App<span class='light'>Blog</span>
    </a>
    <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
      &#9776;
    </button>
    <ul class="nav navbar-nav pull-sm-right hidden-xs-down">
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
      </li>
        <% if admin_signed_in? %>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_admin.name %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to 'My posts', admins_videogames_path, class: "dropdown-item #{yield(:admin)}" %>
                  <%= link_to 'Account', admins_account_path, class: "dropdown-item #{yield(:admin)}" %>
                  <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class: "dropdown-item" %>
              </div>
          </li>
        <% else %>
            <li class="nav-item">
                <a href="/admins/sign_in" class="nav-link">Log in</a>
            </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | AppBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container <%= controller_name%> <%= action_name %>">
        <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | AppBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name%> <%= action_name %>">
        <%= yield %>
    </div>
  </body>
</html>

app/views/user/pages/about.html.erb
<% provide(:page_title, 'About') %>

<h1>About Us</h1>

</br>
</hr>

<h9>Desarrollado por:</h9>
<br>
<h9>Luis Ismael Serrano Galaviz (MasterWicho)</h9>
<br>
<h9>Dylan Haniel Tremillo Toca (dystoland)</h9>

app/views/user/pages/contact.html.erb
<% provide(:page_title, 'Contact') %>

<h5>Nada que ver aquí:3</h5>

app/views/user/videogames/_videogame.html.erb
<div class='col-sm-6 col-lg-4'>
  <div class="card">
      <div class="card-topper" style='background-image: url(<%= videogame.image %>);'></div>
    <div class="card-block">
      <h4 class="card-title"><%= link_to videogame.name, videogame %></h4>
        <p class="published-date"><%= videogame.display_date_published %></p>
        <p class="card-text"><%=truncate(videogame.description, length: 130)%></p>
        <%= link_to 'Read', videogame, class: 'btn btn-read' %>
    </div>
  </div>
</div>

app/views/user/videogames/index.html.erb
<% provide(:page_title, 'Home') %>

<div class="row">
  <%= render @videogames %>
</div>

app/views/user/videogames/show.html.erb
<% provide(:page_title, @videogame.name) %>

<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @videogame.name %></h1>
    <p><%= @videogame.display_date_published %></p>
    <%= @videogame.description%>
  </div>
</div>